apiVersion: v1
kind: Secret
metadata:
  name: sast-ai-dvc-s3-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "your-access-key-id"
  AWS_SECRET_ACCESS_KEY: "your-secret-access-key"
  GIT_REPO_URL: "https://github.com/RHEcosystemAppEng/sast-ai-dvc.git"

